/**
 * E. サティ「ジムノペディ 第 1 番」の音符。
 * scripts/piano-scores.ts で gymnopedie1.mid から作る（直接編集しない）。
 *
 * 音符は Mutopia Project の楽譜（Evin Robertson 作成、底本 Dover Edition、Mutopia-2014/12/14-37、
 * https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=37）の MIDI から変換した。
 * 変更: 反復（\repeat volta と 2 つの括弧）を演奏順に展開した（小節 1〜31、32〜39、1〜31、40〜47）。
 * 時刻と長さを 4 分音符の 1/480 に寄せ、同じ時刻の同じ高さの音を 1 つにまとめた。強弱とテンポは使わない。
 *
 * 原作はパブリックドメイン（Mutopia の表記は Public Domain）。このファイルと gymnopedie1.mid も著作権を主張しない。
 */
import type { ScoreNote } from './types';

/** 1 拍（4 分音符）を 480 に分けた時刻・長さ。1 音 9 文字: 前の音からの間（3）、長さ（3）、音の高さ（2）、譜表（1） */
const DATA =
  'AAAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCAAPAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCA' +
  'APAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCAAAAAHgBOAAHgAHgBRAAHgAHgBPAAAAAWgAmB' +
  'AHgAPAA5AAAAAPAA9AAAAAPABCAAAAAHgBOAAHgAHgBJAAHgAHgBHAAAAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCAAAAAHgBJAAHgAHgBKA' +
  'AHgAWgBFAAAAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAHgBCAAAAAWgArBAHgAPAA7AAAAAPAA-AAAAAWgBCAAPAAWgAmBAHgAPAA5A' +
  'AAAAPAA9AAAAAWgBCAAPAAWgArBAHgAPAA7AAAAAPAA-AAAAAWgBCAAPAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgArBAHgAPAA7A' +
  'AAAAPAA-AAAAAPABCAAAAAHgBOAAHgAHgBRAAHgAHgBPAAAAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAAAAHgBOAAHgAHgBJAAHgAHgBHA' +
  'AAAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCAAAAAHgBJAAHgAHgBKAAHgAWgBFAAAAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgBJA' +
  'AAAAWgAqBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgBOAAAAAWgAjBAHgAPAA7AAAAAPAA-AAAAAPABCAAPABDgBAAAAAAWgAoBAHgAPAA3B' +
  'AAAAPAA7BAPAAWgAoBAHgAPAA7BAAAAPAA-BAAAAPABDBAPAAWgAmBAHgAPAA1BAAAAPAA5BAAAAPAA-BAPAAHgBFAAAAAWgAhBAHgAHgBHA' +
  'AAAAPAA5BAAAAPAA8BAAAAPABABAHgAHgBIAAHgAHgBMAAAAAWgAmBAHgAHgBKAAAAAPAA3BAAAAPAA7BAAAAPABABAHgAHgBHAAHgAHgBKA' +
  'AAAAWgAmBAHgAHgBIAAAAAPAAyBAAAAPAA3BAAAAPAA7BAAAAPABABAHgAHgBHAAHgAlgBKAAAAAWgAmBAHgAPAAwBAAAAPAA0BAAAAPAA5B' +
  'AAAAPAA-BAPAAWgAmBAHgAPAAwBAAAAPAA2BAAAAPAA5BAAAAPAA-BAHgAHgBKAAHgAHgBMAAAAAWgAmBAHgAHgBNAAAAAPAA5BAAAAPAA8B' +
  'AAAAPABBBAHgAHgBPAAHgAHgBRAAAAAWgAmBAHgAHgBIAAAAAPAA5BAAAAPAA8BAAAAPABABAHgAHgBKAAHgAHgBMAAAAAWgAmBAHgAHgBKA' +
  'AAAAPAAyBAAAAPAA3BAAAAPAA7BAAAAPABABAHgAHgBHAAHgAlgBKAAAAAWgAmBAHgAPAAwBAAAAPAA0BAAAAPAA5BAAAAPAA-BAPAAWgAmB' +
  'AHgAPAAwBAAAAPAA2BAAAAPAA5BAAAAPAA-BAHgAHgBKAAHgAWgBPAAAAAWgAoBAHgAPAA7AAAAAPABAAAAAAPABDAAPAAWgBOAAAAAWgAqB' +
  'AHgAPAA5AAAAAPAA9AAAAAPABCAAPAAHgBHAAAAAWgAjBAHgAPAA7AAAAAPAA-AAAAAPABCAAAAAHgBFAAHgAHgBHAAHgAHgBJAAAAAWgAoB' +
  'AHgAPAA9AAAAAPABAAAAAAPABFAAAAAHgBKAAHgAHgBMAAHgAHgBJAAAAAWgAoBAHgAPAA5AAAAAPAA9AAAAAPABCAAAAAPABFAAAAAHgBKA' +
  'AHgAHgBMAAHgAWgBCAAAAAWgAoBAHgAHgA5AAAAAHgA-AAAAAHgAvBAHgAHgA7AAAAAHgA-AAAAAHgBDAAAAAHgA0BAHgAWgA8AAAAAWgBAA' +
  'AAAAWgBFAAAAAWgBIAAAAAWgAtBAAAAWgA3BAWgAWgA-AAAAAWgBCAAAAAWgBFAAAAAWgBKAAAAAWgAmBAAAAWgAtBAAAAWgAyBAWgAWgArB' +
  'AHgAPAA7AAAAAPAA-AAAAAPABCAAPAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCAAPAAWgAmB' +
  'AHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCAAAAAHgBOAAHgAHgBRAAHgAHgBPAAAAAWgAmBAHgAPAA5A' +
  'AAAAPAA9AAAAAPABCAAAAAHgBOAAHgAHgBJAAHgAHgBHAAAAAWgArBAHgAPAA7AAAAAPAA-AAAAAPABCAAAAAHgBJAAHgAHgBKAAHgAWgBFA' +
  'AAAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAHgBCAAAAAWgArBAHgAPAA7AAAAAPAA-AAAAAWgBCAAPAAWgAmBAHgAPAA5AAAAAPAA9A' +
  'AAAAWgBCAAPAAWgArBAHgAPAA7AAAAAPAA-AAAAAWgBCAAPAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgArBAHgAPAA7AAAAAPAA-A' +
  'AAAAPABCAAAAAHgBOAAHgAHgBRAAHgAHgBPAAAAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAAAAHgBOAAHgAHgBJAAHgAHgBHAAAAAWgArB' +
  'AHgAPAA7AAAAAPAA-AAAAAPABCAAAAAHgBJAAHgAHgBKAAHgAWgBFAAAAAWgAmBAHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgBJAAAAAWgAqB' +
  'AHgAPAA5AAAAAPAA9AAAAAPABCAAPAAWgBOAAAAAWgAjBAHgAPAA7AAAAAPAA-AAAAAPABCAAPABDgBAAAAAAWgAoBAHgAPAA3BAAAAPAA7B' +
  'APAAWgAoBAHgAPAA7BAAAAPAA-BAAAAPABDBAPAAWgAmBAHgAPAA1BAAAAPAA5BAAAAPAA-BAPAAHgBFAAAAAWgAhBAHgAHgBHAAAAAPAA5B' +
  'AAAAPAA8BAAAAPABABAHgAHgBIAAHgAHgBMAAAAAWgAmBAHgAHgBKAAAAAPAA3BAAAAPAA7BAAAAPABABAHgAHgBHAAHgAHgBKAAAAAWgAmB' +
  'AHgAHgBIAAAAAPAAyBAAAAPAA3BAAAAPAA7BAAAAPABABAHgAHgBHAAHgAlgBKAAAAAWgAmBAHgAPAAwBAAAAPAA0BAAAAPAA5BAAAAPAA-B' +
  'APAAWgAmBAHgAPAAwBAAAAPAA2BAAAAPAA5BAAAAPAA-BAHgAHgBKAAHgAHgBMAAAAAWgAmBAHgAHgBNAAAAAPAA5BAAAAPAA8BAAAAPABBB' +
  'AHgAHgBPAAHgAHgBRAAAAAWgAmBAHgAHgBIAAAAAPAA5BAAAAPAA8BAAAAPABABAHgAHgBKAAHgAHgBMAAAAAWgAmBAHgAHgBKAAAAAPAAyB' +
  'AAAAPAA3BAAAAPAA7BAAAAPABABAHgAHgBHAAHgAlgBKAAAAAWgAmBAHgAPAAwBAAAAPAA0BAAAAPAA5BAAAAPAA-BAPAAWgAmBAHgAPAAwB' +
  'AAAAPAA2BAAAAPAA5BAAAAPAA-BAHgAHgBKAAHgAWgBPAAAAAWgAoBAHgAPAA7AAAAAPABAAAAAAPABDAAPAAWgBNAAAAAWgAoBAHgAPAA5A' +
  'AAAAPAA-AAAAAPABBAAAAAPABFAAPAAHgBHAAAAAWgAoBAHgAPAA5AAAAAPAA8AAAAAPABBAAAAAHgBIAAHgAHgBNAAHgAHgBMAAAAAWgAoB' +
  'AHgAPAA8AAAAAPABAAAAAAPABFAAAAAHgBKAAHgAHgBIAAHgAHgBMAAAAAWgAoBAHgAPAA5AAAAAPAA8AAAAAPABBAAAAAPABFAAAAAHgBKA' +
  'AHgAHgBIAAHgAWgBBAAAAAWgAoBAHgAHgA5AAAAAHgA-AAAAAHgAvBAHgAHgA7AAAAAHgA-AAAAAHgBDAAAAAHgA0BAHgAWgA8AAAAAWgBAA' +
  'AAAAWgBFAAAAAWgBIAAAAAWgAtBAAAAWgA3BAWgAWgA-AAAAAWgBBAAAAAWgBFAAAAAWgBKAAAAAWgAmBAAAAWgAtBAAAAWgAyB';

const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const v = (s: string) => [...s].reduce((x, c) => x * 64 + A.indexOf(c), 0);

/** テンポの変化: [拍, 基本のテンポに対する比]。最初の項より前の比は 1 */
export const TEMPO: readonly [number, number][] = [];

/** 音符（455 音、78 小節。3/4 拍子） */
export function notes(): ScoreNote[] {
  const out: ScoreNote[] = [];
  let t = 0;
  for (let i = 0; i < DATA.length; i += 9) {
    t += v(DATA.slice(i, i + 3));
    out.push({
      t: t / 480,
      d: v(DATA.slice(i + 3, i + 6)) / 480,
      n: v(DATA.slice(i + 6, i + 8)),
      h: v(DATA[i + 8]),
    });
  }
  return out;
}
