/**
 * L. v. ベートーヴェン「ピアノ・ソナタ 第 14 番 嬰ハ短調 作品 27-2（月光）」より 第 2 楽章の音符。
 * scripts/piano-scores.ts で moonlight2.mid から作る（直接編集しない）。
 *
 * 音符は Mutopia Project の楽譜（Stewart Holmes 作成、底本 Berners, 1908 (edited by A. Winterberger)、
 * Mutopia-2007/02/11-276、https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=276）の MIDI から変換した。
 * 変更: メヌエットの後半、トリオの前半と後半の反復を展開し、トリオのあとにメヌエットを反復なしで繰り返した
 * （Allegretto D. C.）。反復の区切りはどれも 3 拍目の弱起から始まる。
 * 時刻と長さを 4 分音符の 1/480 に寄せ、同じ時刻の同じ高さの音を 1 つにまとめた。強弱とテンポは使わない。
 *
 * このファイルと moonlight2.mid は原作と同じ Creative Commons Attribution-ShareAlike 2.5 Generic
 * （https://creativecommons.org/licenses/by-sa/2.5/）で公開する。リポジトリのほかのファイルの MIT ライセンスは適用しない。
 *
 * SPDX-License-Identifier: CC-BY-SA-2.5
 */
import type { ScoreNote } from './types';

/** 1 拍（4 分音符）を 480 に分けた時刻・長さ。1 音 9 文字: 前の音からの間（3）、長さ（3）、音の高さ（2）、譜表（1） */
const DATA =
  'AAAAHgBEAAAAAHgBJAAAAAHgBBBAHgAPABEAAAAAPABIAAAAAPAA_BAPAAHgBDAAAAAHgBGAAAAAHgA9BAHgAHgBEAAAAAHgBLAAAAAHgA8B' +
  'APAAHgBBAAAAAHgBJAAAAAHgAxBAAAAHgA6BAHgAHgBEAAAAAHgBIAAAAAHgAzBAAAAHgA_BAPAAHgBDAAAAAHgBGAAAAAHgAzBAAAAHgA9B' +
  'AHgAHgBEAAAAAHgA4BAAAAHgA8BAPAAHgBJAAAAAHgBOAAAAAHgBGBAHgAPABJAAAAAPABNAAAAAPABEBAPAAHgBIAAAAAHgBLAAAAAHgBCB' +
  'AHgAHgBJAAAAAHgBQAAAAAHgBBBAPAAHgBGAAAAAHgBOAAAAAHgA2BAAAAHgA_BAHgAHgBJAAAAAHgBNAAAAAHgA4BAAAAHgBEBAPAAHgBIA' +
  'AAAAHgBLAAAAAHgA4BAAAAHgBCBAHgAHgBJAAAAAHgA9BAAAAHgBBBAPAAPAA9AAAAAPABJAAAAAHgA1BAAAAHgA4BAHgAPAAzBAAAAPAA4B' +
  'AHgAHgA8AAAAAHgBIAAHgAHgA6AAAAAPABGAAAAAHgAxBAAAAHgA3BAHgAHgA_AAAAAHgAwBAAAAHgA8BAHgAHgBLAAHgAHgBBAAAAAPABJA' +
  'AAAAHgAxBAAAAHgA6BAHgAHgBEAAAAAHgAzBAAAAHgA_BAHgAHgBIAAHgAHgBDAAAAAPABGAAAAAHgAzBAAAAHgA9BAHgAHgA4BAAAAHgA8B' +
  'AHgAHgBEAAHgAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9BAHgAPAA4BAAAAPAA9BAHgAHgBBAAAAAHgBNAAHgAHgA_AAAAAPABLAAAAAHgA2B' +
  'AAAAHgA8BAHgAHgBEAAAAAHgA1BAAAAHgBBBAHgAHgBQAAHgAHgBGAAAAAPABOAAAAAHgA2BAAAAHgA_BAHgAHgBJAAAAAHgA4BAAAAHgBEB' +
  'AHgAHgBNAAHgAHgBIAAAAAPABLAAAAAHgA4BAAAAHgBCBAHgAHgA9BAAAAHgBBBAHgAHgBJAAHgAHgBBAAAAAHgBJAAAAAHgA9BAHgAPABBA' +
  'AAAAPABJAAAAAPAA6BAPAAHgBBAAAAAHgBJAAAAAHgA4BAHgAPAA_AAAAAHgBJAAAAAHgA3BAHgAHgBIAAAAAHgA4BAHgAHgA_AAAAAHgBHA' +
  'AAAAHgA4BAHgAPAA_AAAAAPABHAAAAAPAA4BAPAAHgA_AAAAAHgBHAAAAAHgA2BAHgAPAA9AAAAAHgBHAAAAAHgA1BAHgAHgBGAAAAAHgA2B' +
  'AHgAHgA9AAAAAHgBGAAAAAHgA2BAHgAPABCAAAAAPABIAAAAAPAAzBAAAAPAA4BAPAAHgBBAAAAAHgBJAAAAAHgAxBAAAAHgA4BAHgAPABCA' +
  'AAAAPABLAAAAAWgAwBAAAAWgA4BAPAAPAA_AAAAAPABCAAHgAPAAxBAAAAPAA4BAHgAHgA9AAAAAHgBBAAHgAHgA6AAAAADwBGAAAAAHgAqB' +
  'AAAADwA2BADwADwBCAAAAADwAzBADwAHgA9AAAAAHgBBAAAAAPAAsBAAAAPAA4BAHgAHgA8AAAAAHgA_AAHgAHgA9AAAAAHgBJAAAAAHgA1B' +
  'AAAAHgA4BAHgAPAA8AAAAAPABIAAAAAPAAzBAAAAPAA4BAPAAHgA6AAAAAHgBGAAAAAHgAxBAAAAHgA3BAHgAHgA_AAAAAHgBLAAAAAHgAwB' +
  'AAAAHgA8BAPAAHgBBAAAAAPABJAAAAAHgAxBAAAAHgA6BAHgAHgBEAAAAAHgAzBAAAAHgA_BAHgAHgBIAAHgAHgBDAAAAAPABGAAAAAHgAzB' +
  'AAAAHgA9BAHgAHgA4BAAAAHgA8BAHgAHgBEAAHgAHgBCAAAAAHgBOAAAAAHgA6BAAAAHgA9BAHgAPABBAAAAAPABNAAAAAPAA4BAAAAPAA9B' +
  'APAAHgA_AAAAAHgBLAAAAAHgA2BAAAAHgA8BAHgAHgBEAAAAAHgBQAAAAAHgA1BAAAAHgA9BAPAAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9B' +
  'AHgAPAA4BAAAAPAA9BAHgAHgBBAAAAAHgBNAAHgAHgA_AAAAAHgBLAAAAAHgA2BAAAAHgA8BAHgAHgBEAAAAAHgBQAAAAAHgA1BAAAAHgA9B' +
  'APAAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9BAHgAPAA4BAAAAPAA9BAHgAHgBBAAAAAHgBNAAHgAPABGAAAAAPABSAAAAAHgA3BAAAAHgA9B' +
  'AAAAHgBABAHgAHgA4BAAAAHgA9BAAAAHgBBBAHgAHgBEAAAAAHgBQAAPAAWgA2AAAAAPAA8AAAAAWgAgBAAAAWgAsBAPAADwA_AADwADwA9A' +
  'ADwAHgA1AAAAAHgA9AAAAAHgAlBAAAAHgAsBAPAAHgBBAAAAAHgBJAAAAAHgA9BAHgAPABBAAAAAPABJAAAAAPAA6BAPAAHgBBAAAAAHgBJA' +
  'AAAAHgA4BAHgAPAA_AAAAAHgBJAAAAAHgA3BAHgAHgBIAAAAAHgA4BAHgAHgA_AAAAAHgBHAAAAAHgA4BAHgAPAA_AAAAAPABHAAAAAPAA4B' +
  'APAAHgA_AAAAAHgBHAAAAAHgA2BAHgAPAA9AAAAAHgBHAAAAAHgA1BAHgAHgBGAAAAAHgA2BAHgAHgA9AAAAAHgBGAAAAAHgA2BAHgAPABCA' +
  'AAAAPABIAAAAAPAAzBAAAAPAA4BAPAAHgBBAAAAAHgBJAAAAAHgAxBAAAAHgA4BAHgAPABCAAAAAPABLAAAAAWgAwBAAAAWgA4BAPAAPAA_A' +
  'AAAAPABCAAHgAPAAxBAAAAPAA4BAHgAHgA9AAAAAHgBBAAHgAHgA6AAAAADwBGAAAAAHgAqBAAAADwA2BADwADwBCAAAAADwAzBADwAHgA9A' +
  'AAAAHgBBAAAAAPAAsBAAAAPAA4BAHgAHgA8AAAAAHgA_AAHgAHgA9AAAAAHgBJAAAAAHgA1BAAAAHgA4BAHgAPAA8AAAAAPABIAAAAAPAAzB' +
  'AAAAPAA4BAPAAHgA6AAAAAHgBGAAAAAHgAxBAAAAHgA3BAHgAHgA_AAAAAHgBLAAAAAHgAwBAAAAHgA8BAPAAHgBBAAAAAPABJAAAAAHgAxB' +
  'AAAAHgA6BAHgAHgBEAAAAAHgAzBAAAAHgA_BAHgAHgBIAAHgAHgBDAAAAAPABGAAAAAHgAzBAAAAHgA9BAHgAHgA4BAAAAHgA8BAHgAHgBEA' +
  'AHgAHgBCAAAAAHgBOAAAAAHgA6BAAAAHgA9BAHgAPABBAAAAAPABNAAAAAPAA4BAAAAPAA9BAPAAHgA_AAAAAHgBLAAAAAHgA2BAAAAHgA8B' +
  'AHgAHgBEAAAAAHgBQAAAAAHgA1BAAAAHgA9BAPAAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9BAHgAPAA4BAAAAPAA9BAHgAHgBBAAAAAHgBNA' +
  'AHgAHgA_AAAAAHgBLAAAAAHgA2BAAAAHgA8BAHgAHgBEAAAAAHgBQAAAAAHgA1BAAAAHgA9BAPAAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9B' +
  'AHgAPAA4BAAAAPAA9BAHgAHgBBAAAAAHgBNAAHgAPABGAAAAAPABSAAAAAHgA3BAAAAHgA9BAAAAHgBABAHgAHgA4BAAAAHgA9BAAAAHgBBB' +
  'AHgAHgBEAAAAAHgBQAAPAAWgA2AAAAAPAA8AAAAAWgAgBAAAAWgAsBAPAADwA_AADwADwA9AADwAHgA1AAAAAHgA9AAAAAHgAlBAAAAHgAsB' +
  'APAAWgA1AAAAAWgBBAAHgAWgAlBAAABaAAsBAPAAWgA2AAAAAWgBCAAHgAWgAnBAPAAPAA_AAAAAPABLAAHgAWgAqBAHgAHgA8AAAAAHgBIA' +
  'AHgAHgA4AAAAAHgBEAAHgAHgA9AAAAAHgBJAAAAAWgApBAHgAHgBBAAAAAHgBNAAHgAWgA1AAAAAWgBBAAHgAWgAlBAAAA8AAsBAPAAWgA2A' +
  'AAAAWgBCAAHgAWgAnBAPAAPABCAAAAAPABOAAHgAPAAgBAHgAHgBGAAAAAHgBSAAHgAHgA8AAAAAHgBIAAAAAWgAsBAHgAHgA_AAAAAHgBLA' +
  'AAAAPAAlBAHgAHgA9AAAAAHgBJAAHgAWgA1AAAAAWgBBAAHgAWgAlBAAABaAAsBAPAAWgA2AAAAAWgBCAAHgAWgAnBAPAAPAA_AAAAAPABLA' +
  'AHgAWgAqBAHgAHgA8AAAAAHgBIAAHgAHgA4AAAAAHgBEAAHgAHgA9AAAAAHgBJAAAAAWgApBAHgAHgBBAAAAAHgBNAAHgAWgA1AAAAAWgBBA' +
  'AHgAWgAlBAAAA8AAsBAPAAWgA2AAAAAWgBCAAHgAWgAnBAPAAPABCAAAAAPABOAAHgAPAAgBAHgAHgBGAAAAAHgBSAAHgAHgA8AAAAAHgBIA' +
  'AAAAWgAsBAHgAHgA_AAAAAHgBLAAAAAPAAlBAHgAHgA9AAAAAHgBJAAHgAWgBBAAAAAWgBNAAHgAWgAyBAAAAWgA4BAPAAWgA6AAAAAWgBGA' +
  'AHgAWgAxBAAAAWgA3BAPAAWgA_AAAAAWgBLAAHgAWgAwBAAAAWgA2BAPAAWgA4AAAAAWgBEAAHgAWgAvBAAAAWgA1BAPAAWgA9AAAAAWgBJA' +
  'AHgAWgAuBAAABaAAxBAPAAWgA2AAAAAWgBCAAHgAWgAsBAPAAPAA1AAAAAPABBAAHgAHgAlBAHgAHgA4AAAAAHgBEAAAAAHgApBAHgAPAA7A' +
  'AAAAPABHAAAAAHgAsBAHgAWgAqBAHgAHgA6AAAAAHgBGAAHgAWgA9AAAAAWgBJAAHgAWgAuBAAABaAAxBAPAAWgA2AAAAAWgBCAAHgAWgAsB' +
  'APAAWgA1AAAAAWgBBAAHgAWgArBAPAAWgA0AAAAAWgBAAAHgAWgAsBAPAAWgA1AAAAAWgBBAAHgAWgAuBAAAAtAAxBAPAAWgA2AAAAAWgBCA' +
  'AHgAlgAsBAPAAPAA1AAAAAPABBAAHgAPAAgBAHgAHgA2AAAAAHgBCAAHgAHgAwAAAAAHgA8AAAAAHgAsBAHgAHgAxAAAAAHgA9AAAAAHgAlB' +
  'APAAWgBBAAAAAWgBNAAHgAWgAyBAAAAWgA4BAPAAWgA6AAAAAWgBGAAHgAWgAxBAAAAWgA3BAPAAWgA_AAAAAWgBLAAHgAWgAwBAAAAWgA2B' +
  'APAAWgA4AAAAAWgBEAAHgAWgAvBAAAAWgA1BAPAAWgA9AAAAAWgBJAAHgAWgAuBAAABaAAxBAPAAWgA2AAAAAWgBCAAHgAWgAsBAPAAPAA1A' +
  'AAAAPABBAAHgAHgAlBAHgAHgA4AAAAAHgBEAAAAAHgApBAHgAPAA7AAAAAPABHAAAAAHgAsBAHgAWgAqBAHgAHgA6AAAAAHgBGAAHgAWgA9A' +
  'AAAAWgBJAAHgAWgAuBAAABaAAxBAPAAWgA2AAAAAWgBCAAHgAWgAsBAPAAWgA1AAAAAWgBBAAHgAWgArBAPAAWgA0AAAAAWgBAAAHgAWgAsB' +
  'APAAWgA1AAAAAWgBBAAHgAWgAuBAAAAtAAxBAPAAWgA2AAAAAWgBCAAHgAlgAsBAPAAPAA1AAAAAPABBAAHgAPAAgBAHgAHgA2AAAAAHgBCA' +
  'AHgAHgAwAAAAAHgA8AAAAAHgAsBAHgAHgAxAAAAAHgA9AAAAAHgAlBAPAAHgBEAAAAAHgBJAAAAAHgBBBAHgAPABEAAAAAPABIAAAAAPAA_B' +
  'APAAHgBDAAAAAHgBGAAAAAHgA9BAHgAHgBEAAAAAHgBLAAAAAHgA8BAPAAHgBBAAAAAHgBJAAAAAHgAxBAAAAHgA6BAHgAHgBEAAAAAHgBIA' +
  'AAAAHgAzBAAAAHgA_BAPAAHgBDAAAAAHgBGAAAAAHgAzBAAAAHgA9BAHgAHgBEAAAAAHgA4BAAAAHgA8BAPAAHgBJAAAAAHgBOAAAAAHgBGB' +
  'AHgAPABJAAAAAPABNAAAAAPABEBAPAAHgBIAAAAAHgBLAAAAAHgBCBAHgAHgBJAAAAAHgBQAAAAAHgBBBAPAAHgBGAAAAAHgBOAAAAAHgA2B' +
  'AAAAHgA_BAHgAHgBJAAAAAHgBNAAAAAHgA4BAAAAHgBEBAPAAHgBIAAAAAHgBLAAAAAHgA4BAAAAHgBCBAHgAHgBJAAAAAHgA9BAAAAHgBBB' +
  'APAAPAA9AAAAAPABJAAAAAHgA1BAAAAHgA4BAHgAPAAzBAAAAPAA4BAHgAHgA8AAAAAHgBIAAHgAHgA6AAAAAPABGAAAAAHgAxBAAAAHgA3B' +
  'AHgAHgA_AAAAAHgAwBAAAAHgA8BAHgAHgBLAAHgAHgBBAAAAAPABJAAAAAHgAxBAAAAHgA6BAHgAHgBEAAAAAHgAzBAAAAHgA_BAHgAHgBIA' +
  'AHgAHgBDAAAAAPABGAAAAAHgAzBAAAAHgA9BAHgAHgA4BAAAAHgA8BAHgAHgBEAAHgAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9BAHgAPAA4B' +
  'AAAAPAA9BAHgAHgBBAAAAAHgBNAAHgAHgA_AAAAAPABLAAAAAHgA2BAAAAHgA8BAHgAHgBEAAAAAHgA1BAAAAHgBBBAHgAHgBQAAHgAHgBGA' +
  'AAAAPABOAAAAAHgA2BAAAAHgA_BAHgAHgBJAAAAAHgA4BAAAAHgBEBAHgAHgBNAAHgAHgBIAAAAAPABLAAAAAHgA4BAAAAHgBCBAHgAHgA9B' +
  'AAAAHgBBBAHgAHgBJAAHgAHgBBAAAAAHgBJAAAAAHgA9BAHgAPABBAAAAAPABJAAAAAPAA6BAPAAHgBBAAAAAHgBJAAAAAHgA4BAHgAPAA_A' +
  'AAAAHgBJAAAAAHgA3BAHgAHgBIAAAAAHgA4BAHgAHgA_AAAAAHgBHAAAAAHgA4BAHgAPAA_AAAAAPABHAAAAAPAA4BAPAAHgA_AAAAAHgBHA' +
  'AAAAHgA2BAHgAPAA9AAAAAHgBHAAAAAHgA1BAHgAHgBGAAAAAHgA2BAHgAHgA9AAAAAHgBGAAAAAHgA2BAHgAPABCAAAAAPABIAAAAAPAAzB' +
  'AAAAPAA4BAPAAHgBBAAAAAHgBJAAAAAHgAxBAAAAHgA4BAHgAPABCAAAAAPABLAAAAAWgAwBAAAAWgA4BAPAAPAA_AAAAAPABCAAHgAPAAxB' +
  'AAAAPAA4BAHgAHgA9AAAAAHgBBAAHgAHgA6AAAAADwBGAAAAAHgAqBAAAADwA2BADwADwBCAAAAADwAzBADwAHgA9AAAAAHgBBAAAAAPAAsB' +
  'AAAAPAA4BAHgAHgA8AAAAAHgA_AAHgAHgA9AAAAAHgBJAAAAAHgA1BAAAAHgA4BAHgAPAA8AAAAAPABIAAAAAPAAzBAAAAPAA4BAPAAHgA6A' +
  'AAAAHgBGAAAAAHgAxBAAAAHgA3BAHgAHgA_AAAAAHgBLAAAAAHgAwBAAAAHgA8BAPAAHgBBAAAAAPABJAAAAAHgAxBAAAAHgA6BAHgAHgBEA' +
  'AAAAHgAzBAAAAHgA_BAHgAHgBIAAHgAHgBDAAAAAPABGAAAAAHgAzBAAAAHgA9BAHgAHgA4BAAAAHgA8BAHgAHgBEAAHgAHgBCAAAAAHgBOA' +
  'AAAAHgA6BAAAAHgA9BAHgAPABBAAAAAPABNAAAAAPAA4BAAAAPAA9BAPAAHgA_AAAAAHgBLAAAAAHgA2BAAAAHgA8BAHgAHgBEAAAAAHgBQA' +
  'AAAAHgA1BAAAAHgA9BAPAAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9BAHgAPAA4BAAAAPAA9BAHgAHgBBAAAAAHgBNAAHgAHgA_AAAAAHgBLA' +
  'AAAAHgA2BAAAAHgA8BAHgAHgBEAAAAAHgBQAAAAAHgA1BAAAAHgA9BAPAAPABCAAAAAPABOAAAAAHgA6BAAAAHgA9BAHgAPAA4BAAAAPAA9B' +
  'AHgAHgBBAAAAAHgBNAAHgAPABGAAAAAPABSAAAAAHgA3BAAAAHgA9BAAAAHgBABAHgAHgA4BAAAAHgA9BAAAAHgBBBAHgAHgBEAAAAAHgBQA' +
  'APAAWgA2AAAAAPAA8AAAAAWgAgBAAAAWgAsBAPAADwA_AADwADwA9AADwAHgA1AAAAAHgA9AAAAAHgAlBAAAAHgAsB';

const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const v = (s: string) => [...s].reduce((x, c) => x * 64 + A.indexOf(c), 0);

/** テンポの変化: [拍, 基本のテンポに対する比]。最初の項より前の比は 1 */
export const TEMPO: readonly [number, number][] = [];

/** 音符（898 音、139 小節と 2 拍。3/4 拍子、最初の 1 拍は弱起） */
export function notes(): ScoreNote[] {
  const out: ScoreNote[] = [];
  let t = 0;
  for (let i = 0; i < DATA.length; i += 9) {
    t += v(DATA.slice(i, i + 3));
    out.push({
      t: t / 480,
      d: v(DATA.slice(i + 3, i + 6)) / 480,
      n: v(DATA.slice(i + 6, i + 8)),
      h: v(DATA[i + 8]),
    });
  }
  return out;
}
