/**
 * J. S. バッハ「目覚めよと呼ぶ声あり BWV 645」（シューブラー・コラール集 第 1 曲）の音符。
 * scripts/organ-scores.ts で bwv645.mid から作る（直接編集しない）。
 *
 * 音符は Mutopia Project の楽譜（Bart Golsteijn 作成、底本 Bach-Gesellschaft, Leipzig、Mutopia-2006/06/29-601、
 * https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=601）の MIDI から変換した。
 * 変更: 反復と第 1・第 2 括弧を演奏順に展開した（弱起と小節 1〜22、2〜20、23〜55。第 1 括弧の 2 小節目（小節 22）は
 * 小節 1 と同じ形で、反復は小節 2 に戻る）。上の譜表（upper）を h = 0、下の譜表（lower、コラールの旋律）を h = 1、
 * ペダルを h = 2 にした。前打音は MIDI では本音符の少し前から元の長さで鳴り、本音符と重なるので、本音符の開始で切った。
 * 時刻と長さを 4 分音符の 1/480 に寄せ、同じ鍵盤で同じ時刻の同じ高さの音を 1 つにまとめた。強弱とテンポは使わない。
 *
 * このファイルと bwv645.mid は原作と同じ Creative Commons Attribution-ShareAlike 2.5 Generic
 * （https://creativecommons.org/licenses/by-sa/2.5/）で公開する。リポジトリのほかのファイルの MIT ライセンスは適用しない。
 *
 * SPDX-License-Identifier: CC-BY-SA-2.5
 */
import type { ScoreNote } from './types';

/** 1 拍（4 分音符）を 480 に分けた時刻・長さ。1 音 9 文字: 前の音からの間（3）、長さ（3）、音の高さ（2）、鍵盤（1） */
const DATA =
  'AAAADwA6AADwAB4A_AAAAAHgAnCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgAnCADwADwBBAADwADwBEAAAAAHgAnCADwADwBDAADwADwA6A' +
  'AAAAHgArCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnCADwADwA_A' +
  'AHgADwA6AADwAB4A_AAAAAHgAnCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgAnCADwADwBBAADwADwBEAAAAAHgAnCADwADwBDAADwADwA6A' +
  'AAAAHgArCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnCADwADwA_A' +
  'AHgADwBGAADwAHgBGAAAAAHgArCAHgAB4BEAAAAAHgAwCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-A' +
  'AB4AB4A8AAB4ADwA6AAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgAnC' +
  'AB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgAuCADwADwBBAADwAHgAyCADwADwA6AADwADwBDAAAAAHgAzCADwAHgBFAADwAHgAyC' +
  'ADwADwBGAACxAA_BBAAA_AB4A_AAAAAHgAwCAB4AB4A-AAB4ADwA_AADwAHgAzCADwADwA8AADwADwBFAAAAAHgA1CADwAHgBGAADwAHgA3C' +
  'ADwADwBIAACxAA_BBAAA_AB4A_AAAAAHgA5CAB4AB4A-AAB4ADwA_AADwAHgA1CADwADwBLAADwAB4BKAAAAAHgA6CAB4AB4BIAAB4ADwBGA' +
  'ADwAB4BGAAAAAHgA5CAB4AB4BFAAB4AFoBGAADwAHgA3CAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4AB4A_AAAAAHgA1CAB4AB4A-AAB4AB4A8A' +
  'AB4AB4A6AAB4AB4A8AAAAAHgAzCAB4AB4A-AAB4ADwA_AACxAA_BBAAA_AB4A_AAAAAHgAyCAB4AB4A-AAB4AFoA_AADwAHgAwCAB4AB4BFA' +
  'AB4AB4BGAAB4AB4BIAAB4AB4BGAAAAAHgAzCAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4ADwBGAAAAADwAyCADwADwBBAAAAADwAuCADwADwA-A' +
  'AAAADwA1CADwAB4A8AAAAADwApCAB4AB4A6AAB4AB4A6AAAAADwArCAB4AB4A_AAB4AB4A-AAAAADwAtCAB4AB4A8AAB4ADwA-AAAAADwAuC' +
  'ADwADwA6AAAAADwAmCACxAA_A5AAA_AFoA3AAAAADwAnCADwADwAkCAB4AB4A5AAB4AFoA5AAAAAHgApCAFoAA8A3AAA8AA8A5AAA8AHgA6A' +
  'AAAADwAuCADwADwAwCADwADwAuCADwADwA6AAAAADwAsCADwAB4A_AAAAADwArCAB4AB4BBAAB4ADwBDAAAAADwApCADwADwBDAAAAADwAnC' +
  'ADwADwBBAAAAADwAmCADwADwBEAAAAAHgAzBAAAAHgAkCADwADwBDAADwADwA6AAAAAHgA3BAAAAHgAwCADwADwA4AADwAB4BDAAAAAHgA6B' +
  'AAAAHgArCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgA6BAAAAHgAuCADwADwA3AADwADwA-AAAAAHgA6BAAAAHgAnCADwADwA_AADwAHgA6B' +
  'AAAAHgArCADwADwA6AADwAB4A_AAAAAPAA8BAAAAHgAsCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgA4CADwADwBBAADwADwBEAAAAAPAA6B' +
  'AAAAHgAyCADwADwBDAADwADwA6AAAAAHgAzCADwADwA4AADwAB4BDAAAAAHgAwCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAyCADwADwA3A' +
  'ADwADwA-AAAAAHgAzCADwADwA_AADwAHgA6BAAAAHgAyCADwADwBBAADwADwBDAAAAAHgA_BAAAAHgAwCADwAHgBFAADwAHgA6BAAAAHgArC' +
  'ADwADwBGAACxAA_BBAAA_AB4A_AAAAADwA_BAAAADwAwCAB4AB4A-AAB4ADwA_AAAAADwBBBAAAADwAyCADwAHgBDBAAAAHgAzCADwADwA_A' +
  'ADwADwBFAAAAALQBBBAAAADwAzCADwAHgBGAAAAADwAyCADwADwArCADwADwBIAAAAADwA_BAAAADwAtCACxAA_BDAAA_AB4BBAAAAAHgA-B' +
  'AAAADwAuCAB4AB4A_AAB4ADwBBAAAAADwAmCADwAFoA8BAAAADwAnCADwADwApCAB4AA8A6BAA8AA8A8BAA8APAA6BAAAADwAuCADwADwAtC' +
  'ADwADwAuCADwADwBGAAAAADwAwCADwAHgBGAAAAADwAyCADwADwAuCADwAB4BEAAAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBA' +
  'AAAAHgAuCAB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgA6BAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgA_BAAAAHgArC' +
  'AB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgA6BAAAAHgAnCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgA8BAAAADwAsC' +
  'ADwADwBBAAAAADwAuCADwAFoA3BAAAAHgAwCAFoAA8A4BAA8AA8A6BAA8ADwA4BAAAAHgApCADwADwA3BADwAHgA1BAAAADwAuCADwADwA6A' +
  'AAAADwAsCADwAB4A_AAAAAPAAzBAAAAHgArCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgAzCADwADwBBAADwADwBEAAAAAHgAyCADwADwBDA' +
  'ADwADwA6AAAAAHgAzCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnC' +
  'ADwADwA_AAHgADwA6AADwAB4A_AAAAAHgAnCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgAnCADwADwBBAADwADwBEAAAAAHgAnCADwADwBDA' +
  'ADwADwA6AAAAAHgArCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnC' +
  'ADwADwA_AAHgADwBGAADwAHgBGAAAAAHgArCAHgAB4BEAAAAAHgAwCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuCAB4AB4A_A' +
  'AB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEA' +
  'AAAAHgAnCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgAuCADwADwBBAADwAHgAyCADwADwA6AADwADwBDAAAAAHgAzCADwAHgBFA' +
  'ADwAHgAyCADwADwBGAACxAA_BBAAA_AB4A_AAAAAHgAwCAB4AB4A-AAB4ADwA_AADwAHgAzCADwADwA8AADwADwBFAAAAAHgA1CADwAHgBGA' +
  'ADwAHgA3CADwADwBIAACxAA_BBAAA_AB4A_AAAAAHgA5CAB4AB4A-AAB4ADwA_AADwAHgA1CADwADwBLAADwAB4BKAAAAAHgA6CAB4AB4BIA' +
  'AB4ADwBGAADwAB4BGAAAAAHgA5CAB4AB4BFAAB4AFoBGAADwAHgA3CAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4AB4A_AAAAAHgA1CAB4AB4A-A' +
  'AB4AB4A8AAB4AB4A6AAB4AB4A8AAAAAHgAzCAB4AB4A-AAB4ADwA_AACxAA_BBAAA_AB4A_AAAAAHgAyCAB4AB4A-AAB4AFoA_AADwAHgAwC' +
  'AB4AB4BFAAB4AB4BGAAB4AB4BIAAB4AB4BGAAAAAHgAzCAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4ADwBGAAAAADwAyCADwADwBBAAAAADwAuC' +
  'ADwADwA-AAAAADwA1CADwAB4A8AAAAADwApCAB4AB4A6AAB4AB4A6AAAAADwArCAB4AB4A_AAB4AB4A-AAAAADwAtCAB4AB4A8AAB4ADwA-A' +
  'AAAADwAuCADwADwA6AAAAADwAmCACxAA_A5AAA_AFoA3AAAAADwAnCADwADwAkCAB4AB4A5AAB4AFoA5AAAAAHgApCAFoAA8A3AAA8AA8A5A' +
  'AA8AHgA6AAAAADwAuCADwADwAwCADwADwAuCADwADwA6AAAAADwAsCADwAB4A_AAAAADwArCAB4AB4BBAAB4ADwBDAAAAADwApCADwADwBDA' +
  'AAAADwAnCADwADwBBAAAAADwAmCADwADwBEAAAAAHgAzBAAAAHgAkCADwADwBDAADwADwA6AAAAAHgA3BAAAAHgAwCADwADwA4AADwAB4BDA' +
  'AAAAHgA6BAAAAHgArCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgA6BAAAAHgAuCADwADwA3AADwADwA-AAAAAHgA6BAAAAHgAnCADwADwA_A' +
  'ADwAHgA6BAAAAHgArCADwADwA6AADwAB4A_AAAAAPAA8BAAAAHgAsCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgA4CADwADwBBAADwADwBEA' +
  'AAAAPAA6BAAAAHgAyCADwADwBDAADwADwA6AAAAAHgAzCADwADwA4AADwAB4BDAAAAAHgAwCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAyC' +
  'ADwADwA3AADwADwA-AAAAAHgAzCADwADwA_AADwAHgA6BAAAAHgAyCADwADwBBAADwADwBDAAAAAHgA_BAAAAHgAwCADwAHgBFAADwAHgA6B' +
  'AAAAHgArCADwADwBGAACxAA_BBAAA_AB4A_AAAAADwA_BAAAADwAwCAB4AB4A-AAB4ADwA_AAAAADwBBBAAAADwAyCADwAHgBDBAAAAHgAzC' +
  'ADwADwA_AADwADwBFAAAAALQBBBAAAADwAzCADwAHgBGAAAAADwAyCADwADwArCADwADwBIAAAAADwA_BAAAADwAtCACxAA_BDAAA_AB4BBA' +
  'AAAAHgA-BAAAADwAuCAB4AB4A_AAB4ADwBBAAAAADwAmCADwAFoA8BAAAADwAnCADwADwApCAB4AA8A6BAA8AA8A8BAA8APAA6BAAAADwAuC' +
  'ADwADwAtCADwADwAuCADwADwBGAAAAADwAwCADwAHgBGAAAAADwAyCADwADwAuCADwAB4BEAAAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_A' +
  'AB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgA6BAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgA_B' +
  'AAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgA6BAAAAHgAnCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgA8B' +
  'AAAADwAsCADwADwBBAAAAADwAuCADwAFoA3BAAAAHgAwCAFoAA8A4BAA8AA8A6BAA8ADwA4BAAAAHgApCADwADwA3BADwAHgA1BAAAADwAuC' +
  'ADwADwBGAAAAADwAsCADwAHgBGAAAAAPAAzBAAAAHgArCAHgAB4BEAAAAAHgAwCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuC' +
  'AB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBA' +
  'AB4AB4BEAAAAAHgAnCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgAuCADwADwBBAADwAHgAyCADwADwA6AADwADwBDAAAAAHgAzC' +
  'ADwAHgBFAADwAHgAyCADwADwBGAACxAA_BBAAA_AB4A_AAAAAHgAwCAB4AB4A-AAB4ADwA_AADwAHgAzCADwADwA8AADwADwBFAAAAAHgA1C' +
  'ADwAHgBGAADwAHgA3CADwADwBIAACxAA_BBAAA_AB4A_AAAAAHgA5CAB4AB4A-AAB4ADwA_AADwAHgA1CADwADwBLAADwAB4BKAAAAAHgA6C' +
  'AB4AB4BIAAB4ADwBGAADwAB4BGAAAAAHgA5CAB4AB4BFAAB4AFoBGAADwAHgA3CAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4AB4A_AAAAAHgA1C' +
  'AB4AB4A-AAB4AB4A8AAB4AB4A6AAB4AB4A8AAAAAHgAzCAB4AB4A-AAB4ADwA_AACxAA_BBAAA_AB4A_AAAAAHgAyCAB4AB4A-AAB4AFoA_A' +
  'ADwAHgAwCAB4AB4BFAAB4AB4BGAAB4AB4BIAAB4AB4BGAAAAAHgAzCAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4ADwBGAAAAADwAyCADwADwBBA' +
  'AAAADwAuCADwADwA-AAAAADwA1CADwAB4A8AAAAADwApCAB4AB4A6AAB4AB4A6AAAAADwArCAB4AB4A_AAB4AB4A-AAAAADwAtCAB4AB4A8A' +
  'AB4ADwA-AAAAADwAuCADwADwA6AAAAADwAmCACxAA_A5AAA_AFoA3AAAAADwAnCADwADwAkCAB4AB4A5AAB4AFoA5AAAAAHgApCAFoAA8A3A' +
  'AA8AA8A5AAA8AHgA6AAAAADwAuCADwADwAwCADwAHgA6BAAAADwAuCADwADwA-AAAAADwAsCADwADwA_AAAAAHgA6BAAAADwArCADwAHgBBA' +
  'AAAADwApCADwAHgA4BAAAADwAnCADwADwBDAAAAADwAmCADwAB4A6AAAAAHgA3BAAAADwAnCAB4AB4A4AAB4ADwA6AAAAADwArCADwAHgA1B' +
  'AAAADwAsCADwADwBGAAAAADwAuCADwAHgBGAAAAAPAAzBAAAADwAwCADwADwAyCADwAB4BEAAAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_A' +
  'AB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgArCAB4AB4BBA' +
  'AB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgA6BAAAAHgAnCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgA6BAAAADwAuCADwADwBBA' +
  'AAAADwAwCADwAHgA4BAAAADwAyCADwADwAuCADwAHgA3BAAAADwAzCADwADwAyCADwAHgA1BAAAADwAwCADwADwBDAAAAADwAvCADwAB4BIA' +
  'AAAAPAAzBAAAADwAwCAB4AB4BKAAB4ADwBLAAAAADwA3CADwADwBLAAAAADwA8CADwADwBKAAAAADwA6CADwADwBNAAAAAHgA4CADwADwBLA' +
  'ADwADwBDAAAAAHgAzCADwADwBBAADwAB4BLAAAAAHgA1CAB4AB4BIAAB4ADwBKAADwADwBBAAAAAHgA3CADwADwA_AADwADwBHAAAAAHgA1B' +
  'AAAADwA4CADwADwBIAAAAADwA3CADwAHgA3BAAAADwA1CADwADwBDAAAAADwA0CADwAHgBDAAAAAPAA4BAAAADwA1CADwADwAzCADwAB4BBA' +
  'AAAADwAyCAB4AB4A_AAB4AB4A-AAAAADwAwCAB4AB4A8AAB4AB4A-AAAAAPAA3BAAAADwAvCAB4AB4A8AAB4AB4A7AAAAADwArCAB4AB4A5A' +
  'AB4ADwA3AAAAADwA3CADwAB4A5AAAAADwA1CAB4AB4A7AAB4AB4A8AAAAAHgAzCAB4AB4A-AAB4AB4A_AAB4AB4A-AAB4AB4BBAAAAAHgAwC' +
  'AB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA_AAAAAHgA3CADwADwA-AADwAHgA7CADwADwA3AADwADwA_AAAAAHgA8CADwAHgBCAADwAHgA6C' +
  'ADwADwBDAACxAA_A-AAA_AB4A8AAAAAHgA5CAB4AB4A6AAB4ADwA8AADwAHgAwCADwADwA5AADwADwBCAAAAAHgAyCADwAHgBDAADwAHgAzC' +
  'ADwADwBFAACxAA_A-AAA_AB4A8AAAAAHgAqCAB4AB4A6AAB4ADwA8AADwAHgAmCADwADwBIAADwAB4BGAAAAAHgArCAB4AB4BFAAB4AFoBDA' +
  'ADwAHgApCAB4AB4BCAAB4AFoBDAADwAHgAzCAB4AB4BBAAB4AB4A_AAB4AB4A-AAB4AB4A8AAAAAHgAyCAB4AB4A6AAB4AB4A5AAB4AB4A3A' +
  'AB4AB4A5AAAAAHgAwCAB4AB4A6AAB4AFoA8AADwAHgAuCAB4AB4A6AAB4AFoA8AADwAHgAtCAB4AB4BCAAB4AB4BDAAB4AB4BFAAB4AB4BDA' +
  'AAAAHgAwCAB4AB4BCAAB4AB4BAAAB4AB4A-AAB4ADwBDAAAAADwAuCADwADwA-AAAAADwArCADwADwA6AAAAADwAyCADwAB4A5AAAAADwAmC' +
  'AB4AB4A3AAB4AHgA3AAAAADwArCADwADwAnCADwAHgA6BAAAADwApCADwADwArCADwAHgA8BAAAADwAsCADwADwArCADwAHgA-BAAAADwAsC' +
  'ADwADwA6AAAAADwAuCADwAB4A_AAAAAPAA_BAAAADwAwCAB4AB4BBAAB4ADwBDAAAAADwAuCADwADwBDAAAAADwAwCADwADwBBAAAAADwAyC' +
  'ADwADwBEAAAAAHgAzCADwADwBDAADwADwA6AAAAAHgAwCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAuC' +
  'ADwADwA3AADwADwA-AAAAADwAwCADwADwA_AAAAADwAuCADwADwA_BAAAADwAwCADwADwBBBAAAADwAyCADwAHgBDBAAAADwAzCADwADwAyC' +
  'ADwAHgBBBAAAADwAzCADwADwBGAAAAADwA1CADwAHgBGAAAAAPAA_BAAAADwA3CADwADwA1CADwAB4BEAAAAADwA3CAB4AB4BDAAB4AB4BBA' +
  'AAAADwA4CAB4AB4A_AAB4AB4BBAAAAADwAyCAB4AB4A_AAB4AB4A-AAAAADwAuCAB4AB4A8AAB4ADwA6AAAAADwA6CADwAB4A8AAAAADwA4C' +
  'AB4AB4A-AAB4AB4A_AAAAAHgA3CAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDA' +
  'AAAADwA6CADwADwBBAAAAADwA4CADwAHgA6BAAAAHgA3CADwADwA_AADwADwBIAAAAAHgA_BAAAAHgA4CADwAHgBKAADwAHgA6BAAAAHgA3C' +
  'ADwADwBLAADwAB4BEAAAAAHgA8BAAAAHgA1CAB4AB4BDAAB4ADwBEAADwAHgA3BAAAAHgAzCADwADwBIAADwADwBKAAAAADwA4BAAAAHgA1C' +
  'ADwAHgBLAAAAADwA3BADwAHgA1BAAAAHgAuCADwADwBNAACxAA_BGAAA_AB4BEAAAAAeAAzBAAAAHgAwCAB4AB4BDAAB4ADwBEAADwAHgAsC' +
  'ADwADwBBAADwAB4BDAAAAAHgAuCAB4AB4BBAAB4AFoA_AADwAHgArCAB4AB4A-AAB4AFoA_AADwADwAsCAB4AB4BJAAB4AB4BIAAAAADwArC' +
  'AB4AB4BGAAB4AB4BEAAAAADwApCAB4AB4BDAAB4AB4BBAAAAADwAnCAB4AB4A_AAB4AB4BBAAAAAHgAmCAB4AB4BDAAB4AFoBEAADwAHgApC' +
  'AB4AB4BDAAB4AFoBEAADwADwAuCAB4AB4A-AAB4AB4A_AAAAADwAwCAB4AB4BBAAB4AB4A_AAAAADwAuCAB4AB4A-AAB4AB4A8AAAAADwAsC' +
  'AB4AB4A6AAB4ADwBGAAAAADwArCADwADwA_AAAAADwAwCADwAB4BDAAAAADwAsCAB4AB4BBAAB4AB4A_AAAAADwAuCAB4AB4A-AAB4AB4A_A' +
  'AAAADwAwCAB4AB4BEAAB4AB4BDAAAAADwAyCAB4AB4BBAAB4ADwBDAAAAADwAzCADwADwA_AAAAADwA3CACxAA_A-AAA_AFoA8AAAAADwA4C' +
  'ADwADwA1CAB4AB4A-AAB4AFoA-AAAAADwA6CADwADwAuCAB4AB4A_AAB4AeAA_AAAAAeAAzC';

const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const v = (s: string) => [...s].reduce((x, c) => x * 64 + A.indexOf(c), 0);

/** テンポの変化: [拍, 基本のテンポに対する比]。最初の項より前の比は 1 */
export const TEMPO: readonly [number, number][] = [];

/** 音符（1160 音、74 小節。4/4 拍子、最初の 0.5 拍は弱起） */
export function notes(): ScoreNote[] {
  const out: ScoreNote[] = [];
  let t = 0;
  for (let i = 0; i < DATA.length; i += 9) {
    t += v(DATA.slice(i, i + 3));
    out.push({
      t: t / 480,
      d: v(DATA.slice(i + 3, i + 6)) / 480,
      n: v(DATA.slice(i + 6, i + 8)),
      h: v(DATA[i + 8]),
    });
  }
  return out;
}
