/**
 * J. S. バッハ「目覚めよと呼ぶ声あり BWV 645」（シューブラー・コラール集 第 1 曲）の音符。
 * scripts/organ-scores.ts で bwv645.mid から作る（直接編集しない）。
 *
 * 音符は Mutopia Project の楽譜（Bart Golsteijn 作成、底本 Bach-Gesellschaft, Leipzig、Mutopia-2006/06/29-601、
 * https://www.mutopiaproject.org/cgibin/piece-info.cgi?id=601）の MIDI から変換した。
 * 変更: 反復と第 1・第 2 括弧を演奏順に展開した（弱起と小節 1〜22、2〜20、23〜55。第 1 括弧の 2 小節目（小節 22）は
 * 小節 1 と同じ形で、反復は小節 2 に戻る）。上の譜表（upper）を h = 0、下の譜表（lower、コラールの旋律）を h = 1、
 * ペダルを h = 2 にした。前打音は MIDI では本音符の少し前から元の長さで鳴り、本音符と重なるので、本音符の開始で切った。
 * MIDI に展開されていない装飾を、.ly の原本（bwv645.ly）の位置と種類で音符に展開した（トリルは上の補助音から
 * 主音と交互に 1 秒に 8〜12 音で弾いて主音で終え、モルデントは主音・下の補助音・主音）。
 * 時刻と長さを 4 分音符の 1/480 に寄せ、同じ鍵盤で同じ時刻の同じ高さの音を 1 つにまとめた。強弱とテンポは使わない。
 *
 * このファイルと bwv645.mid は原作と同じ Creative Commons Attribution-ShareAlike 2.5 Generic
 * （https://creativecommons.org/licenses/by-sa/2.5/）で公開する。リポジトリのほかのファイルの MIT ライセンスは適用しない。
 *
 * SPDX-License-Identifier: CC-BY-SA-2.5
 */
import type { ScoreNote } from './types';

/** 1 拍（4 分音符）を 480 に分けた時刻・長さ。1 音 9 文字: 前の音からの間（3）、長さ（3）、音の高さ（2）、鍵盤（1） */
const DATA =
  'AAAADwA6AADwAB4A_AAAAAHgAnCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgAnCADwADwBBAADwADwBEAAAAAHgAnCADwADwBDAADwADwA6A' +
  'AAAAHgArCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnCADwADwA_A' +
  'AHgADwA6AADwAB4A_AAAAAHgAnCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgAnCADwADwBBAADwADwBEAAAAAHgAnCADwADwBDAADwADwA6A' +
  'AAAAHgArCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnCADwADwA_A' +
  'AHgADwBGAADwAHgBGAAAAAHgArCAHgAB4BEAAAAAHgAwCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-A' +
  'AB4AB4A8AAB4ADwA6AAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgAnC' +
  'AB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgAuCADwADwBBAADwAHgAyCADwADwA6AADwADwBDAAAAAHgAzCADwAHgBFAADwAHgAyC' +
  'ADwADwBGAACxAA_BBAAA_AB4A_AAAAAHgAwCAB4AB4A-AAB4ADwA_AADwAHgAzCADwADwA8AADwADwBFAAAAAHgA1CADwAHgBGAADwAHgA3C' +
  'ADwADwBIAACxAA_BBAAA_AB4A_AAAAAHgA5CAB4AB4A-AAB4ADwA_AADwAHgA1CADwAA8BNAAA8AA8BLAAA8AA8BKAAA8AA8BLAAA8AB4BKA' +
  'AAAAHgA6CAB4AB4BIAAB4ADwBGAADwAA8BIAAAAAHgA5CAA8AA8BGAAA8AB4BFAAB4AFoBGAADwAHgA3CAB4AB4BFAAB4AB4BDAAB4AB4BBA' +
  'AB4AB4A_AAAAAHgA1CAB4AB4A-AAB4AB4A8AAB4AB4A6AAB4AB4A8AAAAAHgAzCAB4AB4A-AAB4ADwA_AACxAA_BBAAA_AB4A_AAAAAHgAyC' +
  'AB4AB4A-AAB4AFoA_AADwAHgAwCAB4AB4BFAAB4AB4BGAAB4AB4BIAAB4AB4BGAAAAAHgAzCAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4ADwBGA' +
  'AAAADwAyCADwADwBBAAAAADwAuCADwAA8A_AAAAADwA1CAA8AA8A-AAA8AA8A_AAA8AA8A-AAA8AB4A8AAAAADwApCAB4AB4A6AAB4AB4A6A' +
  'AAAADwArCAB4AB4A_AAB4AB4A-AAAAADwAtCAB4AB4A8AAB4ADwA-AAAAADwAuCADwADwA6AAAAADwAmCACxAA_A5AAA_AFoA3AAAAADwAnC' +
  'ADwADwAkCAB4AB4A5AAB4AA8A6AAAAAHgApCAA8AA8A5AAA8AA8A6AAA8AA8A5AAA8AA8A6AAA8AA8A5AAA8AA8A3AAA8AA8A5AAA8AHgA6A' +
  'AAAADwAuCADwADwAwCADwADwAuCADwADwA6AAAAADwAsCADwAB4A_AAAAADwArCAB4AB4BBAAB4ADwBDAAAAADwApCADwADwBDAAAAADwAnC' +
  'ADwADwBBAAAAADwAmCADwADwBEAAAAAHgAzBAAAAHgAkCADwADwBDAADwADwA6AAAAAHgA3BAAAAHgAwCADwADwA4AADwAB4BDAAAAAHgA6B' +
  'AAAAHgArCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgA6BAAAAHgAuCADwADwA3AADwADwA-AAAAAHgA6BAAAAHgAnCADwADwA_AADwAHgA6B' +
  'AAAAHgArCADwADwA6AADwAB4A_AAAAAPAA8BAAAAHgAsCAB4AB4BBAAB4ADwBDAADwADwBDAAAAAHgA4CADwADwBBAADwADwBEAAAAAPAA6B' +
  'AAAAHgAyCADwADwBDAADwADwA6AAAAAHgAzCADwADwA4AADwAB4BDAAAAAHgAwCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAyCADwADwA3A' +
  'ADwADwA-AAAAAHgAzCADwADwA_AADwAHgA6BAAAAHgAyCADwADwBBAADwADwBDAAAAAHgA_BAAAAHgAwCADwAHgBFAADwAHgA6BAAAAHgArC' +
  'ADwADwBGAACxAA_BBAAA_AB4A_AAAAADwA_BAAAADwAwCAB4AB4A-AAB4ADwA_AAAAADwBBBAAAADwAyCADwAHgBDBAAAAHgAzCADwADwA_A' +
  'ADwADwBFAAAAALQBBBAAAADwAzCADwAHgBGAAAAADwAyCADwADwArCADwADwBIAAAAADwA_BAAAADwAtCACxAA_BDAAA_AB4BBAAAAAHgA-B' +
  'AAAADwAuCAB4AB4A_AAB4ADwBBAAAAADwAmCADwAA8A-BAAAADwAnCAA8AA8A8BAA8AA8A-BAA8AA8A8BAA8AA8A-BAAAADwApCAA8AA8A8B' +
  'AA8AA8A6BAA8AA8A8BAA8APAA6BAAAADwAuCADwADwAtCADwADwAuCADwADwBGAAAAADwAwCADwAHgBGAAAAADwAyCADwADwAuCADwAB4BEA' +
  'AAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgA6BAAAAHgAsC' +
  'ADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgA_BAAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgA6BAAAAHgAnCAB4AB4BDA' +
  'AB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgA8BAAAADwAsCADwADwBBAAAAADwAuCADwAFoA3BAAAAHgAwCAFoAA8A4BAA8AA8A6BAA8ADwA4B' +
  'AAAAHgApCADwADwA3BADwAHgA1BAAAADwAuCADwADwA6AAAAADwAsCADwAB4A_AAAAAPAAzBAAAAHgArCAB4AB4BBAAB4ADwBDAADwADwBDA' +
  'AAAAHgAzCADwADwBBAADwADwBEAAAAAHgAyCADwADwBDAADwADwA6AAAAAHgAzCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBA' +
  'ADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnCADwADwA_AAHgADwA6AADwAB4A_AAAAAHgAnCAB4AB4BBAAB4ADwBDAADwADwBDA' +
  'AAAAHgAnCADwADwBBAADwADwBEAAAAAHgAnCADwADwBDAADwADwA6AAAAAHgArCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBA' +
  'ADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAAHgAnCADwADwA_AAHgADwBGAADwAHgBGAAAAAHgArCAHgAB4BEAAAAAHgAwCAB4AB4BDA' +
  'AB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_A' +
  'AAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgAnCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgAuCADwADwBBA' +
  'ADwAHgAyCADwADwA6AADwADwBDAAAAAHgAzCADwAHgBFAADwAHgAyCADwADwBGAACxAA_BBAAA_AB4A_AAAAAHgAwCAB4AB4A-AAB4ADwA_A' +
  'ADwAHgAzCADwADwA8AADwADwBFAAAAAHgA1CADwAHgBGAADwAHgA3CADwADwBIAACxAA_BBAAA_AB4A_AAAAAHgA5CAB4AB4A-AAB4ADwA_A' +
  'ADwAHgA1CADwAA8BNAAA8AA8BLAAA8AA8BKAAA8AA8BLAAA8AB4BKAAAAAHgA6CAB4AB4BIAAB4ADwBGAADwAA8BIAAAAAHgA5CAA8AA8BGA' +
  'AA8AB4BFAAB4AFoBGAADwAHgA3CAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4AB4A_AAAAAHgA1CAB4AB4A-AAB4AB4A8AAB4AB4A6AAB4AB4A8A' +
  'AAAAHgAzCAB4AB4A-AAB4ADwA_AACxAA_BBAAA_AB4A_AAAAAHgAyCAB4AB4A-AAB4AFoA_AADwAHgAwCAB4AB4BFAAB4AB4BGAAB4AB4BIA' +
  'AB4AB4BGAAAAAHgAzCAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4ADwBGAAAAADwAyCADwADwBBAAAAADwAuCADwAA8A_AAAAADwA1CAA8AA8A-A' +
  'AA8AA8A_AAA8AA8A-AAA8AB4A8AAAAADwApCAB4AB4A6AAB4AB4A6AAAAADwArCAB4AB4A_AAB4AB4A-AAAAADwAtCAB4AB4A8AAB4ADwA-A' +
  'AAAADwAuCADwADwA6AAAAADwAmCACxAA_A5AAA_AFoA3AAAAADwAnCADwADwAkCAB4AB4A5AAB4AA8A6AAAAAHgApCAA8AA8A5AAA8AA8A6A' +
  'AA8AA8A5AAA8AA8A6AAA8AA8A5AAA8AA8A3AAA8AA8A5AAA8AHgA6AAAAADwAuCADwADwAwCADwADwAuCADwADwA6AAAAADwAsCADwAB4A_A' +
  'AAAADwArCAB4AB4BBAAB4ADwBDAAAAADwApCADwADwBDAAAAADwAnCADwADwBBAAAAADwAmCADwADwBEAAAAAHgAzBAAAAHgAkCADwADwBDA' +
  'ADwADwA6AAAAAHgA3BAAAAHgAwCADwADwA4AADwAB4BDAAAAAHgA6BAAAAHgArCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgA6BAAAAHgAuC' +
  'ADwADwA3AADwADwA-AAAAAHgA6BAAAAHgAnCADwADwA_AADwAHgA6BAAAAHgArCADwADwA6AADwAB4A_AAAAAPAA8BAAAAHgAsCAB4AB4BBA' +
  'AB4ADwBDAADwADwBDAAAAAHgA4CADwADwBBAADwADwBEAAAAAPAA6BAAAAHgAyCADwADwBDAADwADwA6AAAAAHgAzCADwADwA4AADwAB4BDA' +
  'AAAAHgAwCAB4AB4A_AAB4ADwBBAADwADwA4AAAAAHgAyCADwADwA3AADwADwA-AAAAAHgAzCADwADwA_AADwAHgA6BAAAAHgAyCADwADwBBA' +
  'ADwADwBDAAAAAHgA_BAAAAHgAwCADwAHgBFAADwAHgA6BAAAAHgArCADwADwBGAACxAA_BBAAA_AB4A_AAAAADwA_BAAAADwAwCAB4AB4A-A' +
  'AB4ADwA_AAAAADwBBBAAAADwAyCADwAHgBDBAAAAHgAzCADwADwA_AADwADwBFAAAAALQBBBAAAADwAzCADwAHgBGAAAAADwAyCADwADwArC' +
  'ADwADwBIAAAAADwA_BAAAADwAtCACxAA_BDAAA_AB4BBAAAAAHgA-BAAAADwAuCAB4AB4A_AAB4ADwBBAAAAADwAmCADwAA8A-BAAAADwAnC' +
  'AA8AA8A8BAA8AA8A-BAA8AA8A8BAA8AA8A-BAAAADwApCAA8AA8A8BAA8AA8A6BAA8AA8A8BAA8APAA6BAAAADwAuCADwADwAtCADwADwAuC' +
  'ADwADwBGAAAAADwAwCADwAHgBGAAAAADwAyCADwADwAuCADwAB4BEAAAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuC' +
  'AB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgA6BAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgA_BAAAAHgArCAB4AB4BBA' +
  'AB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgA6BAAAAHgAnCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgA8BAAAADwAsCADwADwBBA' +
  'AAAADwAuCADwAFoA3BAAAAHgAwCAFoAA8A4BAA8AA8A6BAA8ADwA4BAAAAHgApCADwADwA3BADwAHgA1BAAAADwAuCADwADwBGAAAAADwAsC' +
  'ADwAHgBGAAAAAPAAzBAAAAHgArCAHgAB4BEAAAAAHgAwCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-A' +
  'AB4AB4A8AAB4ADwA6AAAAAHgAsCADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgAnC' +
  'AB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAAHgAuCADwADwBBAADwAHgAyCADwADwA6AADwADwBDAAAAAHgAzCADwAHgBFAADwAHgAyC' +
  'ADwADwBGAACxAA_BBAAA_AB4A_AAAAAHgAwCAB4AB4A-AAB4ADwA_AADwAHgAzCADwADwA8AADwADwBFAAAAAHgA1CADwAHgBGAADwAHgA3C' +
  'ADwADwBIAACxAA_BBAAA_AB4A_AAAAAHgA5CAB4AB4A-AAB4ADwA_AADwAHgA1CADwADwBLAADwAB4BKAAAAAHgA6CAB4AB4BIAAB4ADwBGA' +
  'ADwAA8BIAAAAAHgA5CAA8AA8BGAAA8AB4BFAAB4AFoBGAADwAHgA3CAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4AB4A_AAAAAHgA1CAB4AB4A-A' +
  'AB4AB4A8AAB4AB4A6AAB4AB4A8AAAAAHgAzCAB4AB4A-AAB4ADwA_AACxAA_BBAAA_AB4A_AAAAAHgAyCAB4AB4A-AAB4AFoA_AADwAHgAwC' +
  'AB4AB4BFAAB4AB4BGAAB4AB4BIAAB4AB4BGAAAAAHgAzCAB4AB4BFAAB4AB4BDAAB4AB4BBAAB4ADwBGAAAAADwAyCADwADwBBAAAAADwAuC' +
  'ADwAA8A_AAAAADwA1CAA8AA8A-AAA8AA8A_AAA8AA8A-AAA8AB4A8AAAAADwApCAB4AB4A6AAB4AB4A6AAAAADwArCAB4AB4A_AAB4AB4A-A' +
  'AAAADwAtCAB4AB4A8AAB4ADwA-AAAAADwAuCADwADwA6AAAAADwAmCACxAA_A5AAA_AFoA3AAAAADwAnCADwADwAkCAB4AB4A5AAB4AA8A6A' +
  'AAAAHgApCAA8AA8A5AAA8AA8A6AAA8AA8A5AAA8AA8A6AAA8AA8A5AAA8AA8A3AAA8AA8A5AAA8AHgA6AAAAADwAuCADwADwAwCADwAHgA6B' +
  'AAAADwAuCADwADwA-AAAAADwAsCADwADwA_AAAAAHgA6BAAAADwArCADwAHgBBAAAAADwApCADwAHgA4BAAAADwAnCADwADwBDAAAAADwAmC' +
  'ADwAA8A8AAAAAHgA3BAAAADwAnCAA8AA8A6AAA8AB4A4AAB4ADwA6AAAAADwArCADwAAwA3BAAAADwAsCAAwAAwA1BAAwAAwA3BAAwAAwA1B' +
  'AAwAAwA3BAAwADwBGAAAAAAwA1BAAAADwAuCAAwAAwA3BAAwAAwA1BAAwAAwA3BAAwAAwA1BAAwAHgBGAAAAAPAAzBAAAADwAwCADwADwAyC' +
  'ADwAB4BEAAAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4AB4BBAAAAAHgAuCAB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA6AAAAAHgAsC' +
  'ADwAB4A8AAB4AB4A-AAB4AB4A_AAAAAHgArCAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgA6BAAAAHgAnCAB4AB4BDAAB4AB4BBA' +
  'AB4AB4A_AAB4ADwBDAAAAAHgA6BAAAADwAuCADwADwBBAAAAADwAwCADwAHgA4BAAAADwAyCADwADwAuCADwAHgA3BAAAADwAzCADwADwAyC' +
  'ADwAAwA3BAAAADwAwCAAwAAwA1BAAwAAwA3BAAwAAwA1BAAwAAwA3BAAwADwBDAAAAAAwA1BAAAADwAvCAAwAAwA3BAAwAAwA1BAAwAAwA3B' +
  'AAwAAwA1BAAwAB4BIAAAAAPAAzBAAAADwAwCAB4AB4BKAAB4ADwBLAAAAADwA3CADwADwBLAAAAADwA8CADwADwBKAAAAADwA6CADwADwBNA' +
  'AAAAHgA4CADwADwBLAADwADwBDAAAAAHgAzCADwADwBBAADwAB4BLAAAAAHgA1CAB4AB4BIAAB4ADwBKAADwADwBBAAAAAHgA3CADwADwA_A' +
  'ADwADwBHAAAAAHgA1BAAAADwA4CADwADwBIAAAAADwA3CADwAHgA3BAAAADwA1CADwADwBDAAAAADwA0CADwAHgBDAAAAAA1A6BAAAADwA1C' +
  'AA1AA2A4BAA2AA1A6BAA1AA1A4BAA1AA2A6BAAbADwAzCAAbAA1A4BAA1AA1A6BAA1AA2A4BAA2AA1A6BAA1AB4BBAAAAAA1A4BAAAADwAyC' +
  'AA1AA2A6BAA2AA1A4BAANAB4A_AAAoAA1A6BAA1AA2A4BAAbAB4A-AAAAADwAwCAAbAA1A6BAA1AA1A4BAAoAB4A8AAANAA2A6BAA2AA1A4B' +
  'AA1AB4A-AAAAAPAA3BAAAADwAvCAB4AB4A8AAB4AB4A7AAAAADwArCAB4AB4A5AAB4ADwA3AAAAADwA3CADwAB4A5AAAAADwA1CAB4AB4A7A' +
  'AB4AB4A8AAAAAHgAzCAB4AB4A-AAB4AB4A_AAB4AB4A-AAB4AB4BBAAAAAHgAwCAB4AB4A_AAB4AB4A-AAB4AB4A8AAB4ADwA_AAAAAHgA3C' +
  'ADwADwA-AADwAHgA7CADwADwA3AADwADwA_AAAAAHgA8CADwAHgBCAADwAHgA6CADwADwBDAACxAA_A-AAA_AB4A8AAAAAHgA5CAB4AB4A6A' +
  'AB4ADwA8AADwAHgAwCADwADwA5AADwADwBCAAAAAHgAyCADwAHgBDAADwAHgAzCADwADwBFAACxAA_A-AAA_AB4A8AAAAAHgAqCAB4AB4A6A' +
  'AB4ADwA8AADwAHgAmCADwADwBIAADwAB4BGAAAAAHgArCAB4AB4BFAAB4ADwBDAADwAA8BFAAAAAHgApCAA8AA8BDAAA8AB4BCAAB4AFoBDA' +
  'ADwAHgAzCAB4AB4BBAAB4AB4A_AAB4AB4A-AAB4AB4A8AAAAAHgAyCAB4AB4A6AAB4AB4A5AAB4AB4A3AAB4AB4A5AAAAAHgAwCAB4AB4A6A' +
  'AB4ADwA8AADwAA8A-AAAAAHgAuCAA8AA8A8AAA8AB4A6AAB4AFoA8AADwAHgAtCAB4AB4BCAAB4AB4BDAAB4AB4BFAAB4AB4BDAAAAAHgAwC' +
  'AB4AB4BCAAB4AB4BAAAB4AB4A-AAB4ADwBDAAAAADwAuCADwADwA-AAAAADwArCADwAA8A8AAAAADwAyCAA8AA8A6AAA8AA8A8AAA8AA8A6A' +
  'AA8AB4A5AAAAADwAmCAB4AB4A3AAB4AHgA3AAAAADwArCADwADwAnCADwAHgA6BAAAADwApCADwADwArCADwAHgA8BAAAADwAsCADwADwArC' +
  'ADwAHgA-BAAAADwAsCADwADwA6AAAAADwAuCADwAB4A_AAAAAPAA_BAAAADwAwCAB4AB4BBAAB4ADwBDAAAAADwAuCADwADwBDAAAAADwAwC' +
  'ADwADwBBAAAAADwAyCADwADwBEAAAAAHgAzCADwADwBDAADwADwA6AAAAAHgAwCADwADwA4AADwAB4BDAAAAAHgAsCAB4AB4A_AAB4ADwBBA' +
  'ADwADwA4AAAAAHgAuCADwADwA3AADwADwA-AAAAADwAwCADwADwA_AAAAADwAuCADwADwA_BAAAADwAwCADwADwBBBAAAADwAyCADwAHgBDB' +
  'AAAADwAzCADwADwAyCADwAAwBDBAAAADwAzCAAwAAwBBBAAwAAwBDBAAwAAwBBBAAwAAwBDBAAwADwBGAAAAAAwBBBAAAADwA1CAAwAAwBDB' +
  'AAwAAwBBBAAwAAwBDBAAwAAwBBBAAwAHgBGAAAAAPAA_BAAAADwA3CADwADwA1CADwAB4BEAAAAADwA3CAB4AB4BDAAB4AB4BBAAAAADwA4C' +
  'AB4AB4A_AAB4AB4BBAAAAADwAyCAB4AB4A_AAB4AB4A-AAAAADwAuCAB4AB4A8AAB4ADwA6AAAAADwA6CADwAB4A8AAAAADwA4CAB4AB4A-A' +
  'AB4AB4A_AAAAAHgA3CAB4AB4BBAAB4AB4BDAAB4AB4BBAAB4AB4BEAAAAAHgAzCAB4AB4BDAAB4AB4BBAAB4AB4A_AAB4ADwBDAAAAADwA6C' +
  'ADwADwBBAAAAADwA4CADwAHgA6BAAAAHgA3CADwADwA_AADwADwBIAAAAAHgA_BAAAAHgA4CADwAHgBKAADwAHgA6BAAAAHgA3CADwADwBLA' +
  'ADwAA8BGAAAAAHgA8BAAAAHgA1CAA8AA8BEAAA8AB4BDAAB4ADwBEAADwAHgA3BAAAAHgAzCADwADwBIAADwADwBKAAAAADwA4BAAAAHgA1C' +
  'ADwAHgBLAAAAADwA3BADwAAwA3BAAAAHgAuCAAwAAwA1BAAwAAwA3BAAwAAwA1BAAwAAwA3BAAwADwBNAAAAAAwA1BAAwAAwA3BAAwAAwA1B' +
  'AAwAAwA3BAAhAA_BGAAAPAAwA1BAAwAB4BEAAAAAeAAzBAAAAHgAwCAB4AB4BDAAB4ADwBEAADwAHgAsCADwADwBBAADwAB4BDAAAAAHgAuC' +
  'AB4AB4BBAAB4ADwA_AADwAA8BBAAAAAHgArCAA8AA8A_AAA8AB4A-AAB4AFoA_AADwADwAsCAB4AB4BJAAB4AB4BIAAAAADwArCAB4AB4BGA' +
  'AB4AB4BEAAAAADwApCAB4AB4BDAAB4AB4BBAAAAADwAnCAB4AB4A_AAB4AB4BBAAAAAHgAmCAB4AB4BDAAB4ADwBEAADwAA8BGAAAAAHgApC' +
  'AA8AA8BEAAA8AB4BDAAB4AFoBEAADwADwAuCAB4AB4A-AAB4AB4A_AAAAADwAwCAB4AB4BBAAB4AB4A_AAAAADwAuCAB4AB4A-AAB4AB4A8A' +
  'AAAADwAsCAB4AB4A6AAB4ADwBGAAAAADwArCADwADwA_AAAAADwAwCADwAB4BDAAAAADwAsCAB4AB4BBAAB4AB4A_AAAAADwAuCAB4AB4A-A' +
  'AB4AB4A_AAAAADwAwCAB4AB4BEAAB4AB4BDAAAAADwAyCAB4AB4BBAAB4ADwBDAAAAADwAzCADwADwA_AAAAADwA3CACxAA_A-AAA_AFoA8A' +
  'AAAADwA4CADwADwA1CAB4AB4A-AAB4AFoA-AAAAADwA6CADwADwAuCAB4AB4A_AAB4AeAA_AAAAAeAAzC';

const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const v = (s: string) => [...s].reduce((x, c) => x * 64 + A.indexOf(c), 0);

/** テンポの変化: [拍, 基本のテンポに対する比]。最初の項より前の比は 1 */
export const TEMPO: readonly [number, number][] = [];

/** 音符（1269 音、74 小節。4/4 拍子、最初の 0.5 拍は弱起） */
export function notes(): ScoreNote[] {
  const out: ScoreNote[] = [];
  let t = 0;
  for (let i = 0; i < DATA.length; i += 9) {
    t += v(DATA.slice(i, i + 3));
    out.push({
      t: t / 480,
      d: v(DATA.slice(i + 3, i + 6)) / 480,
      n: v(DATA.slice(i + 6, i + 8)),
      h: v(DATA[i + 8]),
    });
  }
  return out;
}
